spring.application.name=cria

spring.datasource.url=jdbc:mysql://localhost:3306/cria_app
spring.datasource.username=lucasdev
spring.datasource.password=lucasdev

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
