package com.test.cria.exception;

public enum ErrorCodeEnum {
    INVALID_USER_ID,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    EMPLOYEE_NOT_FOUND,
    CLASSROOM_NOT_FOUND,
    CLASSROOM_ALREADY_EXISTS,
    VALIDATION_FAILED,
    RESOURCE_NOT_FOUND,
    INVALID_PARAMETER_TYPE,
    INVALID_CLASSROOM_CONFIGURATION,
    MISSING_PATH_VARIABLE,
    METHOD_NOT_ALLOWED
}
